### ISSUE TITLE
G_train not defined in your notebook : '10_data_loader.ipynb'

### ISSUE THREAD

**Issue by Ujjwalsas9** [waittim/graph-fraud-detection#1]
Hi, could you please complete the notebook as I think its missing the line where you have defined 'G_train'. It would be really helpful.

Thanks.

**Comment by waittim** [comment]
Hi, the cell including `G_train` is unnecessary, and the `G_train` won't be used in the following steps. Please ignore that cell.
I keep it just to record a potential way of visualizing a graph.
